In [1]:
import mxnet as mx
from mxnet import nd

In [44]:
x = nd.arange(12, ctx=mx.gpu())
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @gpu(0)>

In [39]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [45]:
x.shape

(12,)

In [46]:
x.size

12

In [47]:
X = x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @gpu(0)>

In [6]:
X.size

12

In [7]:
X = x.reshape((-1,2))
X


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
<NDArray 6x2 @gpu(0)>

In [7]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [8]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
Y = nd.array([[2,1,3,4],[2,5,8,9],[4,1,5,2]], ctx=mx.gpu())
Y


[[2. 1. 3. 4.]
 [2. 5. 8. 9.]
 [4. 1. 5. 2.]]
<NDArray 3x4 @gpu(0)>

In [10]:
Z = nd.random.normal(0,1,shape=(3, 4), ctx=mx.gpu())
Z


[[-1.3204551   0.68232244 -0.9858383   0.01992839]
 [ 0.7842404   0.50066984 -1.0283492   0.98445743]
 [ 0.23791966  0.5675242   0.416008    1.2724396 ]]
<NDArray 3x4 @gpu(0)>

In [11]:
X+Y


[[ 2.  2.  5.  7.]
 [ 6. 10. 14. 16.]
 [12. 10. 15. 13.]]
<NDArray 3x4 @gpu(0)>

In [12]:
X*Y


[[ 0.  1.  6. 12.]
 [ 8. 25. 48. 63.]
 [32.  9. 50. 22.]]
<NDArray 3x4 @gpu(0)>

In [13]:
X/Y


[[0.        1.        0.6666667 0.75     ]
 [2.        1.        0.75      0.7777778]
 [2.        9.        2.        5.5      ]]
<NDArray 3x4 @gpu(0)>

In [14]:
Y.exp()


[[7.3890562e+00 2.7182817e+00 2.0085537e+01 5.4598148e+01]
 [7.3890562e+00 1.4841316e+02 2.9809580e+03 8.1030840e+03]
 [5.4598148e+01 2.7182817e+00 1.4841316e+02 7.3890562e+00]]
<NDArray 3x4 @gpu(0)>

In [17]:
nd.dot(X,Y.T)


[[ 19.  48.  17.]
 [ 59. 144.  65.]
 [ 99. 240. 113.]]
<NDArray 3x3 @gpu(0)>

In [18]:
nd.concat(X,Y,dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  3.  4.]
 [ 2.  5.  8.  9.]
 [ 4.  1.  5.  2.]]
<NDArray 6x4 @gpu(0)>

In [20]:
nd.concat(X,Y,dim=1)


[[ 0.  1.  2.  3.  2.  1.  3.  4.]
 [ 4.  5.  6.  7.  2.  5.  8.  9.]
 [ 8.  9. 10. 11.  4.  1.  5.  2.]]
<NDArray 3x8 @gpu(0)>

In [21]:
X == Y


[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @gpu(0)>

In [22]:
X.sum()


[66.]
<NDArray 1 @gpu(0)>

In [23]:
Y.sum()


[46.]
<NDArray 1 @gpu(0)>

In [24]:
Y.norm()


[15.811388]
<NDArray 1 @gpu(0)>

In [25]:
X.norm().asscalar()

22.494444

In [27]:
A = nd.arange(3).reshape(3,1)
B = nd.arange(2).reshape(1,2)
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [28]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [29]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @gpu(0)>

In [48]:
X[1,2]


[6.]
<NDArray 1 @gpu(0)>

In [49]:
X[1:2,0:3] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @gpu(0)>