In [1]:
import mxnet as mx
from mxnet import nd

In [2]:
x = nd.arange(12, ctx=mx.gpu())
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @gpu(0)>

In [39]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape

(12,)

In [4]:
x.size

12

In [5]:
X = x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @gpu(0)>

In [6]:
X.size

12

In [7]:
X = x.reshape((-1,2))
X


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
<NDArray 6x2 @gpu(0)>

In [7]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [8]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [6]:
Y = nd.array([[2,1,3,4],[2,5,8,9],[4,1,5,2]], ctx=mx.gpu())
Y


[[2. 1. 3. 4.]
 [2. 5. 8. 9.]
 [4. 1. 5. 2.]]
<NDArray 3x4 @gpu(0)>

In [10]:
Z = nd.random.normal(0,1,shape=(3, 4), ctx=mx.gpu())
Z


[[-1.3204551   0.68232244 -0.9858383   0.01992839]
 [ 0.7842404   0.50066984 -1.0283492   0.98445743]
 [ 0.23791966  0.5675242   0.416008    1.2724396 ]]
<NDArray 3x4 @gpu(0)>

In [11]:
X+Y


[[ 2.  2.  5.  7.]
 [ 6. 10. 14. 16.]
 [12. 10. 15. 13.]]
<NDArray 3x4 @gpu(0)>

In [12]:
X*Y


[[ 0.  1.  6. 12.]
 [ 8. 25. 48. 63.]
 [32.  9. 50. 22.]]
<NDArray 3x4 @gpu(0)>

In [13]:
X/Y


[[0.        1.        0.6666667 0.75     ]
 [2.        1.        0.75      0.7777778]
 [2.        9.        2.        5.5      ]]
<NDArray 3x4 @gpu(0)>

In [14]:
Y.exp()


[[7.3890562e+00 2.7182817e+00 2.0085537e+01 5.4598148e+01]
 [7.3890562e+00 1.4841316e+02 2.9809580e+03 8.1030840e+03]
 [5.4598148e+01 2.7182817e+00 1.4841316e+02 7.3890562e+00]]
<NDArray 3x4 @gpu(0)>

In [17]:
nd.dot(X,Y.T)


[[ 19.  48.  17.]
 [ 59. 144.  65.]
 [ 99. 240. 113.]]
<NDArray 3x3 @gpu(0)>

In [18]:
nd.concat(X,Y,dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  3.  4.]
 [ 2.  5.  8.  9.]
 [ 4.  1.  5.  2.]]
<NDArray 6x4 @gpu(0)>

In [20]:
nd.concat(X,Y,dim=1)


[[ 0.  1.  2.  3.  2.  1.  3.  4.]
 [ 4.  5.  6.  7.  2.  5.  8.  9.]
 [ 8.  9. 10. 11.  4.  1.  5.  2.]]
<NDArray 3x8 @gpu(0)>

In [21]:
X == Y


[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @gpu(0)>

In [22]:
X.sum()


[66.]
<NDArray 1 @gpu(0)>

In [23]:
Y.sum()


[46.]
<NDArray 1 @gpu(0)>

In [24]:
Y.norm()


[15.811388]
<NDArray 1 @gpu(0)>

In [25]:
X.norm().asscalar()

22.494444

In [27]:
A = nd.arange(3).reshape(3,1)
B = nd.arange(2).reshape(1,2)
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [28]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [29]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @gpu(0)>

In [48]:
X[1,2]


[6.]
<NDArray 1 @gpu(0)>

In [49]:
X[1:2,0:3] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @gpu(0)>

In [7]:
before = id(Y)

Y=Y+X
now = id(Y)

In [8]:
before, now

(2096070271720, 2096955513880)

In [9]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X+Y
id(Z)==before

True

In [10]:
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

In [11]:
before = id(X)
X += Y
id(X) == before

True

In [14]:
import numpy as np
P = np.ones((2, 3))
D = nd.array(P,ctx=mx.gpu())
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @gpu(0)>

In [15]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [23]:
X<=Y


[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @gpu(0)>

In [ ]:
## ⾃动求梯度

In [24]:
from mxnet import autograd, nd

In [25]:
x = nd.arange(4).reshape((4, 1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [27]:
# 为了求有关变量x的梯度，我们需要先调⽤attach_grad函数来申请存储梯度所需要的内存。
x.attach_grad()

In [28]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [29]:
# 接下来我们可以通过调⽤backward函数⾃动求梯度。需要注意的是，如果y不是⼀个标量，MXNet将默认先对y中元素求和得到新的变量，再求该变量有关x的梯度。
y.backward()

In [30]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [31]:
print(dir(nd.random))

['NDArray', '_Null', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_internal', '_random_helper', 'current_context', 'exponential', 'gamma', 'generalized_negative_binomial', 'multinomial', 'negative_binomial', 'normal', 'numeric_types', 'poisson', 'shuffle', 'uniform']


In [35]:
nd.random.normal()


[0.29956347]
<NDArray 1 @cpu(0)>

In [36]:
help(nd.ones_like)

Help on function ones_like:

ones_like(data=None, out=None, name=None, **kwargs)
    Return an array of ones with the same shape and type
    as the input array.
    
    Examples::
    
      x = [[ 0.,  0.,  0.],
           [ 0.,  0.,  0.]]
    
      ones_like(x) = [[ 1.,  1.,  1.],
                      [ 1.,  1.,  1.]]
    
    
    
    Parameters
    ----------
    data : NDArray
        The input
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.



In [37]:
help(nd.random.normal)

Help on function normal in module mxnet.ndarray.random:

normal(loc=0, scale=1, shape=_Null, dtype=_Null, ctx=None, out=None, **kwargs)
    Draw random samples from a normal (Gaussian) distribution.
    
    Samples are distributed according to a normal distribution parametrized
    by *loc* (mean) and *scale* (standard deviation).
    
    
    Parameters
    ----------
    loc : float or NDArray
        Mean (centre) of the distribution.
    scale : float or NDArray
        Standard deviation (spread or width) of the distribution.
    shape : int or tuple of ints
        The number of samples to draw. If shape is, e.g., `(m, n)` and `loc` and
        `scale` are scalars, output shape will be `(m, n)`. If `loc` and `scale`
        are NDArrays with shape, e.g., `(x, y)`, then output will have shape
        `(x, y, m, n)`, where `m*n` samples are drawn for each `[loc, scale)` pair.
    dtype : {'float16','float32', 'float64'}
        Data type of output samples. Default is 'float32'
  